### PR TITLE
Add Synapse icon and JSON data

### PR DESCRIPTION
**Pull request by tschaffter**
**Brand Name:** Synapse
**Website:** https://www.synapse.org/
**Alexa rank:** [726,836](https://www.alexa.com/siteinfo/synapse.org)
  

**Official resources for icon and color:** -

### CODE REVIEW

**Comment by tschaffter** [comment]
From the Contribution Guide:

Using your preferred tool you should:

- [x] Isolate the icon from any text or extraneous items.
- [x] Merge any overlapping paths.
- [x] Compound all paths into one.
- [x] Change the icon's viewbox/canvas/page size to 24x24.
- [x] Scale the icon to fit the viewbox, while preserving the icon's original proportions. This means the icon should be touching at least two sides of the viewbox.
- [x] Center the icon horizontally and vertically.
- [x] Remove all colors. The icon should be monochromatic.
- [x] Export the icon as an SVG.

**Comment by tschaffter** [comment]
From the Contribution Guide:

- [x] [Annotate the Icon](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#4-annotate-the-icon)

Here is the content of the svg file:

```
<?xml version="1.0" encoding="utf-8"?>
<!-- Generator: Adobe Illustrator 25.2.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
<svg version="1.1" id="Layer_1" xmlns:svg="http://www.w3.org/2000/svg" role="img"
         xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 24 24"
         style="enable-background:new 0 0 24 24;" xml:space="preserve">
<title>Synapse icon</title>
<style type="text/css">
        .st0{fill-rule:evenodd;clip-rule:evenodd;}
</style>
<path class="st0" d="M21,16.3c-0.3-0.1-0.5-0.3-0.8-0.3l0-7.8c0.3-0.1,0.7-0.2,1-0.4c2-1.1,2.7-3.7,1.5-5.6c-1.1-2-3.7-2.6-5.7-1.5
        c-1.7,1-2.5,3.1-1.9,4.9L7.9,9.7C6.7,8.2,4.5,7.8,2.8,8.9c-2,1.1-2.7,3.7-1.5,5.6c1.1,2,3.7,2.6,5.7,1.5c0.2-0.1,0.5-0.3,0.7-0.5
        l7.2,4.1c-0.1,1.5,0.6,3,2,3.8c2,1.1,4.5,0.4,5.7-1.5C23.7,19.9,23,17.4,21,16.3z M18.1,2.3c1-0.6,2.3-0.2,2.8,0.7
        c0.6,1,0.2,2.2-0.8,2.8c-0.7,0.4-1.7,0.3-2.3-0.1c-0.2-0.2-0.4-0.4-0.5-0.6C16.8,4.2,17.1,2.9,18.1,2.3z M5.9,14.2
        c-1,0.6-2.3,0.2-2.8-0.7c-0.3-0.5-0.3-1-0.2-1.6c0.1-0.5,0.5-1,1-1.3c0.5-0.3,1-0.3,1.5-0.2c0.5,0.1,1,0.5,1.3,1
        c0.3,0.5,0.4,1.2,0.2,1.7C6.6,13.6,6.3,13.9,5.9,14.2z M15.5,17.6l-6.8-3.9C9,13.1,9,12.3,8.9,11.5l7.5-4.4c0.5,0.5,1.1,0.8,1.8,1
        l0,7.7C17.1,16,16.1,16.7,15.5,17.6z M20.7,20.9c-0.6,1-1.8,1.3-2.8,0.8c-1-0.6-1.3-1.8-0.8-2.8c0.6-1,1.8-1.3,2.8-0.8
        C21,18.6,21.3,19.9,20.7,20.9z"/>
</svg>
```

**Comment by tschaffter** [comment]
From the Contribution Guide:

- [x] [Update the JSON Data for SimpleIcons.org](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#6-update-the-json-data-for-simpleiconsorg)

I specified the blue color of the wide banner from the home page (see below) as the Synapse primary "brand color" (`"hex": "2B688F"`).

image

**Comment by tschaffter** [comment]
From the Contribution Guide:

- [x] [Optimize the Icon](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#3-optimize-the-icon)

```
$ npm ci
$ npm run svgo -- icons/synapse.svg

> simple-icons@4.13.0 svgo
> svgo --config svgo.config.js "icons/synapse.svg"


synapse.svg:
Done in 20 ms!
1.359 KiB - 40.6% = 0.808 KiB
```

I then opened the icon with Adobe Illustrator (AI). The icon was no longer filling the artboard so I resized it and saved. This removed the annotations added previously to the svg file so I added them again.

**Comment by tschaffter** [comment]
@jay-hodgson @lbradic I prepared the icon following the [contribution guide of the Simple Icons](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md). This PR documents the operations that I performed to prepare the icon.

The submission to Simple Icons is composed of three elements:

- PR information (first comment of this PR)
- Synapse logo in SVG format
- Synapse logo metadata

I will submit these three element once you have accepted this PR (after rebasing this branch to include recent commits from Simple Icons).

**Review by jay-hodgson — APPROVED** [review]
Looks good to me!  viewBox set to 24x24, single path definition with no fill colors.  Nice work :)
Initially, I thought they would not want the **title** element to be included ("Isolate the icon from any text or extraneous items."), but I now see that a **title** has been included in other submissions.

**Comment by tschaffter** [comment]
Finalizing this PR and will make the submission to Simple Icons following approval from Jay and Ljubo.

**Pull request merged**
